name: Gitleaks Secrets Scan

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --report-path=gitleaks-report.json --exit-code=1 --verbose

      - name: Upload Gitleaks report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: gitleaks-report.json
