name: OWASP Dependency-Check

on:
  push:
    branches: [ main, master ] #
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "MyProject"
          format: "ALL"
          out: "reports"
          scan: "."

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4  
        with:
          name: dependency-check-report
          path: reports
