# .github/workflows/semgrep.yml
name: Semgrep

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install latest Semgrep via pip (instead of using old action version)
      - name: Install latest Semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade semgrep

      # Run semgrep scan manually
      - name: Run Semgrep
        run: |
          semgrep --config auto --error --verbose
